server:
  port: 8080

beer:
  svc:
    host:
      inventory: http://localhost:8082
spring:
  application:
    name: beer-service
  artemis:
    #defaults for docker image vromero/activemq-artemis
    user: artemis
    password: simetraehcapa
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: EMBEDDED
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  cache:
    jcache:
      config: classpath:ehcache.xml
  cloud:
    discovery:
      enabled: true
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    service:
      name: ${spring.application.name}

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    root: info


