server:
  port: 8080

beer:
  svc:
    host:
      inventory: http://localhost:8082
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: EMBEDDED
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: info
