server:
  port: 8080

beer:
  svc:
    host:
      inventory: http://localhost:8082

spring:
  datasource:
    initialization-mode: EMBEDDED
  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: info
